### ISSUE TITLE
The program won't run

### ISSUE THREAD

**Issue by beijita-yegucheng** [eurecom-asp/rawnet2-antispoofing#1]
sysid_dict_inv {0: '-', 1: 'A01', 2: 'A02', 3: 'A03', 4: 'A04', 5: 'A05', 6: 'A06'}
data_root E:/Downloads/DS_10283_3336/LA/ASVspoof2019_LA_cm_protocols
dset_name train
protocols_fname train.trl
protocols_dir E:/Downloads/DS_10283_3336/LA/ASVspoof2019_LA_cm_protocols
files_dir E:/Downloads/DS_10283_3336/LA/ASVspoof2019_LA_train\flac
protocols_file E:/Downloads/DS_10283_3336/LA/ASVspoof2019_LA_cm_protocols\ASVspoof2019.LA.cm.train.trl.txt
cache_fname cache_train_LA_Raw_audio.npy
Dear author, why does the program stay on top when I run the training model？

**Comment by TakHemlata** [comment]
Hi, we fixed a bug of model definition, and tested the code on our server again, and it's running without problem.

We are not sure if that bug stopped your code, could you please send your error to my email so we can fix it?

Also, we don't get what do you mean by 'stay on top', you mean to say the code is still running or stopped because of bug? If it is still running, the feature preparation progress will normally take some time for train and dev data, and after that, training will start automatically.  


thanks

**Comment by beijita-yegucheng** [comment]
Dear author, thank you for your reply so soon. I think I already know how to solve this problem. Thank you again for your help.

Another question, can you describe the SVM _ Fusion. M , how does this code run and how to fuse multiple Eval score files?

**Comment by beijita-yegucheng** [comment]
My current problem is how to get better scores through fusion. Thank you very much for your reply!

thanks

**Comment by josepatino** [comment]
Dear Beijita,
we'd like to refer you to reading the comments included in the SVM_fusion/SVM_fusion.m MATLAB script.
Best regards
